name: first WorkFlow

on:
  workflow_dispatch:
  
 jobs:
   firstjob:
     runs-on: self-hosted
     steps:
       - name: firstJob script
         shell: bash
         run: echo Hello World! This is the first job
         
   secondjob:
     runs-on: self-hosted
     steps:
       - name: secondJob script
         shell: bash
         run: |
           echo this is second job 
           echo and this is a multi-line script
